sport/main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
]

sport/sport/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^.*', include('main.urls')),
]

sport/wiki/urls.py
from django.conf.urls import url
from wiki import views


urlpatterns = [
    url(r'^$', views.wiki, name='wiki'),
    url(r'^category/(?P<categoryID>[0-9]+)/$', views.category, name='category'),
    url(r'^addCategory/$', views.addCategory, name='addCategory'),
    url(r'^addPage/(?P<categoryID>[0-9]+)/$', views.addPage, name='addPage'),
    url(r'^deleteCategory/(?P<categoryID>[0-9]+)/$', views.deleteCategory,
        name='deleteCategory'),
    url(r'^deletePage/(?P<pageID>[0-9]+)/$', views.deletePage,
        name='deletePage'),
    url(r'^updateCategory/(?P<categoryID>[0-9]+)/$', views.updateCategory,
        name='updateCategory'),
    url(r'^updatePage/(?P<pageID>[0-9]+)/$', views.updatePage,
        name='updatePage'),
]

sport/main/models.py
from django.db import models

# Create your models here.

sport/wiki/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name
    
    
class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128, unique=True)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    

sport/wiki/forms.py
from django import forms
from wiki.models import Category, Page


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, label='分类名称', help_text='请输入视频分类名称')
    
    class Meta:
        model = Category
        fields = ('name', )
        
        
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, label='网页标题', help_text='请输入网页标题')
    url = forms.URLField(max_length=128, label='网页网址', help_text='请输入网页网址')
    
    class Meta:
        model = Page
        exclude = ('category', 'views')
    def clean(self):
        cleanedData = self.cleaned_data
        url = cleanedData.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleanedData['url'] = url
        return cleanedData

sport/main/views.py
from django.shortcuts import render
import datetime


def main(request):
    context = {'message':'Django very good', }
    return render(request, 'main/main.html', context)

# Create your views here.

sport/wiki/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from wiki.models import Category, Page
from wiki.forms import CategoryForm, PageForm


def wiki(request):
    categories = Category.objects.order_by('-likes')
    context = {'categories': categories}
    return render(request, 'wiki/wiki.html',context)
def category(request, categoryID):
    context = {}
    try:
        category = Category.objects.get(id=categoryID)
        context['category']=category
        context['pages']= Page.objects.filter(category = category)
    except Category.DoesNotExist:
        pass
    return render(request, 'wiki/category.html', context)


def addCategory(request):
    template = 'wiki/addCategory.html'
    if request.method=='GET':
        return render(request, template, {'form':CategoryForm()})
    # request.method=='POST'
    form = CategoryForm(request.POST)
    if not form.is_valid():
        return render(request, template, {'form':form})
    form.save()
    return redirect(reverse('wiki:wiki'))
    # Or try this: return wiki(request)

def addPage(request, categoryID):
    template = 'wiki/addPage.html'
    try:
        pageCategory = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return category(request, categoryID)
    context = {'category':pageCategory}
    if request.method=='GET':
        context['form'] = PageForm()
        return render(request, template, context)
    # request.method=='POST'
    form = PageForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, template, context)
    page = form.save(commit=False)
    page.category = pageCategory
    page.save()
    return redirect(reverse('wiki:category', args=(categoryID, )))
def deleteCategory(request, categoryID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    categoryToDelete = Category.objects.get(id=categoryID)
    if categoryToDelete:
        categoryToDelete.delete()
    return redirect(reverse('wiki:wiki'))
def deletePage(request, pageID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    pageToDelete = Page.objects.get(id=pageID)
    if pageToDelete:
        categoryID = pageToDelete.category.id
        pageToDelete.delete()
    else:
        categoryID = ''
    return redirect(reverse('wiki:category', args=(categoryID, )))
def updateCategory(request, categoryID):
    template = 'wiki/updateCategory.html'
    try:
        category = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return wiki(request)
    if request.method=='GET':
        form = CategoryForm(instance=category)
        return render(request, template, {'form':form, 'category':category})
    # request.method=='POST'
    form = CategoryForm(request.POST, instance=category)
    if not form.is_valid():
        return render(request, template, {'form':form, 'category':category})
    category.save()
    return redirect(reverse('wiki:wiki'))
def updatePage(request, pageID):
    template = 'wiki/updatePage.html'
    try:
        page = Page.objects.get(id=pageID)
    except Page.DoesNotExist:
        return category(request, '')
    if request.method=='GET':
        form = PageForm(instance=page)
        return render(request, template, {'form':form, 'page':page})
    # request.method=='POST'
    form = PageForm(request.POST, instance=page)
    if not form.is_valid():
        return render(request, template, {'form':form, 'page':page})
    page.save()
    return redirect(reverse('wiki:category', args=(page.category.id,)))        

sport/main/templates/main/main.html
<!doctype html>
<html>
<head>
<title>视频导航</title>
<meta charset=utf-8>
</head>
<body>
<h1>Django 說--Hello world!</h1>
<p>{{message}}</p>
<p><a href={% url 'wiki:wiki' %}>前往 Wiki 網頁</a></p>
</body>
</html>

sport/wiki/templates/wiki/addCategory.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>视频导航</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>新增视频分类</h1>
<form method=post action={% url 'wiki:addCategory' %}>
{% csrf_token %}
{{form.as_p}}
<input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:wiki' %}>回 Wiki 页面</a></p>
</body>
</html>

sport/wiki/templates/wiki/addPage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>视频导航</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>在"{{category.name}}"分类中新增一个网页</h1>
<form method=post action={% url 'wiki:addPage' category.id %}>
{% csrf_token %}
{{form.as_p}}
<input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:category' category.id %}>回{{category.name}}页面
</a></p>
</body>
</html>

sport/wiki/templates/wiki/category.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>视频导航</title>
<meta charset=utf-8>
<link rel=stylesheet href="{% static 'main/css/main.css' %}">
</head>
<body>
{% if category %}
 <h1>{{category.name}}</h1>
 {% if pages %}
 <table>
 <tr><th>网页标题</th></tr>
 {% for page in pages %}
 <tr>
 <td>
    <a href={{page.url}}>{{page.title}}</a>
 </td>
 <td>
    <form action={% url 'wiki:updatePage' page.id %}>
      <input type=submit value=修改>
    </form>
 </td>
 <td>
  <form method=post action={% url 'wiki:deletePage' page.id %}>
    {% csrf_token %}
    <input type=submit value=刪除>
  </form>
 </td>
 </tr>
 {% endfor %}
 </table>
 {% else %}
 <p><strong>目前尚无此项目资料</strong></p>
 {% endif %}
 <p><a href={% url 'wiki:addPage' category.id %}>新增网页</a></p>
{% else %}
 <p>所指定的项目「{{categoryID}}」不存在。</p>
{% endif %}
<br>
<p><a href={% url 'wiki:wiki' %}>回 Wiki 网页</a></p>
</body>
</html>

sport/wiki/templates/wiki/updateCategory.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>视频导航</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>修改视频分类</h1>
<form method=post action={% url 'wiki:updateCategory' category.id %}>
{% csrf_token %}
{{form.as_p}}
<input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:wiki' %}>回 Wiki 页面</a></p>
</body>
</html>

sport/wiki/templates/wiki/updatePage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>视频导航</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>修改页面</h1>
<form method=post action={% url 'wiki:updatePage' page.id %}>
{% csrf_token %}
{{form.as_p}}
<input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:category' page.category.id %}>回「{{page.category.name}}」页面
</a></p>
</body>
</html>

sport/wiki/templates/wiki/wiki.html
<!doctype html>
<html>
<head>
<title>视频导航</title>
<meta charset=utf-8>
</head>
<body>
<h1>Welcom to Wiki！</h1>
{% if categories %}
 <h2>视频分类：</h2>
    <table>
    <tr><th>分类名称</th><th></th><th></th></tr>
      {% for category in categories %}
       <tr>
         <td>
          <a href={% url 'wiki:category' category.id %}>{{category.name}}</a>
         </td>
         <td>
         <form action={% url 'wiki:updateCategory' category.id %}>
           <input type="submit" value=修改>
         </form>
         </td>
         <td>
            <form method=post action={% url 'wiki:deleteCategory' category.id %}>
              {% csrf_token %}
              <input type=submit value=刪除>
            </form>
        </td>
       </tr>
      {% endfor %}
    </table>
{% else %}
 <p><strong>目前尚未建立视频分类。</strong></p>
{% endif %}
<br>
<a href={% url 'wiki:addCategory' %}>新增视频分类</a></p>
<p><a href={% url 'main:main' %}>回首页</a></p>
</body>
</html>